[project]
name = "amazons3securitystorage"
version = "0.1.0"
description = ""
authors = [
    { name = "Your Name", email = "you@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "fastapi",
    "sqlalchemy[asyncio]",
    "aiosqlite",
    "python-jose[cryptography]",
    "bcrypt",
    "python-multipart",
    "asyncpg",
    "pydantic[email]",
    "uvicorn[standard]",
    "alembic",
    "boto3 (>=1.42.96,<2.0.0)",
    "pydantic-settings (>=2.14.0,<3.0.0)",
    "slowapi (>=0.1.9,<0.2.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"